### ISSUE TITLE
Missing or_default method

### ISSUE THREAD

**Issue by renatoathaydes** [contain-rs/linked-hash-map#107]
Hi,
I've had to replace a `HashMap` with a `LinkedHashMap` and my code broke where I was using [`map.entry(key).or_default()`](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.or_default).

That's a pretty common method for grouping things together using a `Vec` for example.

Would be a nice addition to this lib.

**Comment by Gankra** [comment]
added in 0.5.5
