### ISSUE TITLE
Inserting a existing key will change the order of keys

### ISSUE THREAD

**Issue by ptazithos** [contain-rs/linked-hash-map#111]
# Description:
Inserting a exising key will change the order of keys.
```rust
let mut map = LinkedHashMap::new();
map.insert("a",0);
map.insert("b",1);
map.insert("c",2);
```
Now, the order of the keys is "a", "b" and "c".
Then we update the value of "b" by insert method:
```rust
map.insert("b",0);
```
The order of the keys changes to "a", "c" and "b".
Intutively, I think the the behavior of `map.insert("b",0);` should be equivalent to `map["b"] = 0;` except the way they handle exceptions.
Is this a feature or a bug?

**Comment by probablykasper** [comment]
I would say it's expected. Values are stored in insertion order, so when I call `.insert()` I'd expect it to be ordered last

**Comment by ptazithos** [comment]
> I would say it's expected. Values are stored in insertion order, so when I call `.insert()` I'd expect it to be ordered last

That makes sense. Thank you!
