### ISSUE TITLE
Return removed value in pop_front

### ISSUE THREAD

**Issue by fenhl** [contain-rs/linked-hash-map#17]
The method name of `pop_front` is misleading since it does not return the removed value. Changing this would also make the method more useful.

**Comment by Gankro** [comment]
Can you provide a concrete usecase?

**Comment by fenhl** [comment]
I am trying to implement `IntoIterator` for a type wrapping `LinkedHashMap`, which would be very easy with this, although #4 would also help.

**Comment by arthurprs** [comment]
This is frequently used inside other data structures so we should expose as much as we can without crossing rivers.
A great use case is caches where you want to take some action with the expired item.
