### ISSUE TITLE
crates.io not updated

### ISSUE THREAD

**Issue by GuillaumeGomez** [contain-rs/linked-hash-map#18]
Hey,

Could you publish the current version of this repo please ? Lru-cache needs it and it can't build right now. Thanks !

**Comment by arthurprs** [comment]
This repo definitely needs some love

**Comment by Gankro** [comment]
Whoops, I thought I did this!

**Comment by Gankro** [comment]
0.0.3 released

**Comment by GuillaumeGomez** [comment]
Thanks !
