### ISSUE TITLE
Consider make it build with stable rustc

### ISSUE THREAD

**Issue by zonyitoo** [contain-rs/linked-hash-map#28]
Currently it rely on these 3 unstable features:

```rust
#![feature(hashmap_hasher)]
#![feature(box_raw)]
#![feature(iter_order)]
```

Could it be replaced by some stable features to make it build with stable rustc.

**Comment by apasel422** [comment]
`box_raw` is stable now, and `iter_order` can easily be `cfg`-ed off with a `nightly` feature (or worked around), but eliminating `hashmap_hasher` would require removing the `S` parameter from `LinkedHashMap`. I'm not opposed to this, as it doesn't seem like that feature is going to be stabilized any time soon, but it's a significant change.

**Comment by zonyitoo** [comment]
Maybe you guys could ask the official team to stabilize the `hashmap_hasher`?

**Comment by apasel422** [comment]
The exact API hasn't been chosen yet. See rust-lang/rust#27713.

**Comment by fenhl** [comment]
The above issue is now in its final comment period and will likely be stabilized in Rust 1.6.

**Comment by dylanede** [comment]
Just a note that this still doesn't build on stable.

**Comment by apasel422** [comment]
This isn't going to build on stable until 1.7 is released, but with that in
mind, I would accept a PR that enables testing on beta in Travis.

**Comment by reem** [comment]
In the meantime I am maintaining a very small and temporary fork that works on stable [here](https://github.com/terminalcloud/linked-hash-map), available on crates.io as `terminal-linked-hash-map`; do note that I plan to stop maintaining this fork as soon as this crate can build on stable.

**Comment by apasel422** [comment]
With the release of Rust 1.7, this appears to build on stable.
