### ISSUE TITLE
Investigate augmenting `RawTable` directly

### ISSUE THREAD

**Issue by apasel422** [contain-rs/linked-hash-map#30]
This crate wraps `HashMap` to provide ordered iteration with very little additional code, but its approach is essentially a hack and requires additional heap allocation in order to work. We should consider augmenting `RawTable` with a type parameter in order to implement this more efficiently. Normal `HashMap`s would use `()` internally for this parameter, while `LinkedHashMap` would use a `struct Link { next: usize, prev: usize }`.

CC @Gankro.

**Comment by Gankro** [comment]
As in you want upstream to expose RawTable?

**Comment by apasel422** [comment]
More like having `std` itself provide `LinkedHashMap` instead of hacking on top of it as this crate currently does.

**Comment by apasel422** [comment]
What I want to do here is define `RawTable` as:
```rust
struct RawTable<K, V, A = ()> {
    capacity: usize,
    size: usize,
    hashes: Unique<u64>, // dynamic allocation of `cap` `u64`s | `cap` `K`s | `cap` `V`s | `cap` `A`s
    aug: A, // used to store the head/tail indices for the linked version
    marker: marker::PhantomData<(K, V)>,
}
```
and then
```rust
struct Link {
    next: usize,
    prev: usize,
}

pub struct LinkedHashMap<K, V> {
    table: RawTable<K, V, Link>,
    ...
}
```
This will let us remove the extra key/value indirection in the current impl along with the dummy node, though the performance implications remain to be determined.

**Comment by Gankro** [comment]
Forking std's impl seems more viable, honestly.

**Comment by apasel422** [comment]
I think we should look into this, even if it involves maintaining an internal copy of `RawTable` for the time being.

CC @carllerche.

**Comment by carllerche** [comment]
To follow up, I extracted the hash table as a standalone library that runs on stable Rust. https://github.com/carllerche/hash-table
