### ISSUE TITLE
Investigate contiguous ordered map implementation

### ISSUE THREAD

**Issue by Veedrac** [contain-rs/linked-hash-map#46]
There is [a PyPy blog post](http://morepypy.blogspot.co.uk/2015/01/faster-more-memory-efficient-and-more.html) explaining their ordered, contiguous dictionaries. This means they'll be a lot faster than a linked implementation; PyPy even found it was competitive with their prior unordered implementation.

In essence you replace the linked list with a mostly compact vector, on the basis that insertions only add to the end and deletions are dealt with using occasional recompacting.

An implementation where `sparse_array` is a `HashMap<KeyRef<K>, usize>` would work, though it duplicates the information in the key and value. `LinkedHashMap` does too, so that's not much of a showstopper, though it is unfortunate.

**Comment by arthurprs** [comment]
`HashMap<KeyRef<K>, usize>` would still require the (K, V) pairs in the Vec to be boxed so I doubt we would get any gains this way.
