### ISSUE TITLE
Avoid allocating uninitialized memory for list head

### ISSUE THREAD

**Issue by apasel422** [contain-rs/linked-hash-map#6]

**Comment by arthurprs** [comment]
This was solved in PR #25

**Comment by apasel422** [comment]
Hmm. `LinkedHashMap::insert` still uses uninitialized memory, so I'm no sure about closing this.

**Comment by Gankro** [comment]
What else can be done? Just ditching the dummy-node altogether (e.g. as linkedList does)?

**Comment by apasel422** [comment]
Not sure anything can be done. This issue can be closed if you're satisfied
with the current solution; I was just pointing out that the new code still
uses uninitialized memory.

**Comment by arthurprs** [comment]
Keep it open. I think there's room for improvement in the future.
Em 05/07/2015 21:41, "Andrew Paseltiner" <notifications@github.com>
escreveu:

**Comment by apasel422** [comment]
Closing in favor of #30.
