### ISSUE TITLE
upgrade to serde 1.0

### ISSUE THREAD

**Issue by vitiral** [contain-rs/linked-hash-map#86]
As far as I know, this library is the primary mechanism for using sorted hashmaps in serde. As such it is a bottleneck for my serialization needs.

I can submit a PR, but I wanted to make sure you are around to merge it.

**Comment by vitiral** [comment]
nevermind, it looks like I can just use a `BTreeMap` instead. I won't be submitting a PR for this, but it would still be nice if this lib could be updated if someone had custom ordering needs.

**Comment by palfrey** [comment]
Done as of 92c4fc5fbbf7bca8ba93643f7631c0a147558872

**Comment by est31** [comment]
This can be closed, @Gankra @huonw.
